### ISSUE TITLE
Create "upstream" and "STScI" labels?

### ISSUE THREAD

**Issue by smythp** [Iota-School/notebooks-for-all#25]
## Problem and context

Something I've noticed while going through the issues is that some (like the suggestion to link to the source notebook) would more likely be specific to STScI, while others might be potential candidates for an upstream PR or issue on nb-convert. Should we create labels for these as well, or would we be getting ahead of ourselves?

## Possible solutions

We could either create labels for `STScI Improvement` and `Potential upstream`, or we could avoid the proliferation of new labels.

## Acceptance criteria

We will close this task when a decision is made on the usefulness of more labels.

**Comment by isabela-pf** [comment]
Because I don't expect most of my contributions will take PR form regularly, I don't think this will heavily impact me either way. 

I could see this being a helpful tag for planning/splitting up work, or for reporting and tracking what we do. Other than that, I'm pretty neutral. This is also easy to undo if we decide later it is creating issues.

**Comment by tonyfast** [comment]
i agree on this process. closing. lets reopen when if it becomes relevant.
